//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebParser
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class u0979199_springer_dataEntities1 : DbContext
    {
        public u0979199_springer_dataEntities1()
            : base("name=u0979199_springer_dataEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<authors> authors { get; set; }
        public virtual DbSet<keywords> keywords { get; set; }
        public virtual DbSet<publications> publications { get; set; }
        public virtual DbSet<sources> sources { get; set; }
        public virtual DbSet<types> types { get; set; }
    }
}
