//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebParser
{
    using System;
    using System.Collections.Generic;
    
    public partial class sources
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sources()
        {
            this.publications = new HashSet<publications>();
        }
    
        public int id { get; set; }
        public string item_title { get; set; }
        public string book_series_title { get; set; }
        public Nullable<int> journal_volume { get; set; }
        public Nullable<int> journal_issue { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<publications> publications { get; set; }
    }
}
